### ISSUE TITLE
Mail to hydrogen bounces

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen-music#12]
Reported by @sciurius [here](https://github.com/hydrogen-music/hydrogen/issues/836):

> info@hydrogen-music.org: Host or domain name not found. Name service error
> for name=mail.hydrogen-music.org type=A: Host not found

**Comment by mauser** [comment]
I'm closing this issue since this mail adress is not shown anymore on the web page (and it doesn't exist).
