### ISSUE TITLE
Auto-Adjust Song When Inserting/Removing Patterns (Not a new issue, just a question) 

### ISSUE THREAD

**Issue by realto619** [hydrogen-music/hydrogen-music#21]
![HydrogenAutoAdjust](https://user-images.githubusercontent.com/318644/131953183-5efa02af-9ca9-4dc4-b56e-0270fce2e84c.png)
Is there a way to insert or remove a pattern from an existing song and have the rest of the patterns auto-adjust to accommodate the change(s)?  Currently when I want to change an existing song I have to manually move every pattern individually and it's a real PITA, not to mention inspirationally stifling. Especially when it's a song with close to 100 different patterns. Or is there a smarter way to approach this problem? 

Love the program overall. Great work!

Thanks in advance, 
Paul Leech

**Comment by realto619** [comment]
![HydrogenAutoAdjust_Answer](https://user-images.githubusercontent.com/318644/131954156-a4e4253d-05ac-4e85-95e7-13dc34dc8710.png)
Okay, I just answered my own question. For anyone else that may come across this, if you click the Select button, you can select the patterns you want to move and drag them accordingly. I tried that before but it didn't work. So, of course, after I actually write up a question about it, then it works! Hahahaha.... Thanks!

**Comment by realto619** [comment]
Since this has been resolved, I'm closing it. Sorry for any inconvenience!

**Comment by cme** [comment]
Yeah, the next release will have the "select" behaviour as the default rather than the alternate mode, since it should be easier to "discover"!
