### ISSUE TITLE
remove kxstudio mention on hydrogen-music.org

### ISSUE THREAD

**Issue by wolftune** [hydrogen-music/hydrogen-music#22]
KXStudio doesn't include Hydrogen any longer

**Comment by theGreatWhiteShark** [comment]
Do you by any chance know about the reason why this step was taken? At least from our perspective the application is getting more and more stable and we didn't introduced new dependencies.

**Comment by wolftune** [comment]
It's old news by now, from 2 years ago:

https://kx.studio/News/?action=view&url=the-kxstudio-are-slowly-coming-back

>  Audio plugins (including standalone synths and FX) are the focus of the repos.
>  General applications and tools will not be supported anymore.

So it had nothing to do with Hydrogen specifically. KXStudio is focused now only on a few sets of apps, mainly from falktx himself and otherwise plugins and not apps.

It was too much for him to manage the scope of apps and growing demand for more apps and so on

**Comment by wolftune** [comment]
I might add that this does make it a notably higher burden for many GNU/Linux users to readily use updated Hydrogen unfortunately.

**Comment by theGreatWhiteShark** [comment]
> It was too much for him to manage the scope of apps and growing demand for more apps and so on

Ah, I see.

> I might add that this does make it a notably higher burden for many GNU/Linux users to readily use updated Hydrogen unfortunately.

Well, only users of KXStudio are affected. Lot's of other distributions do ship (more or less recent versions of ) hydrogen.
