### ISSUE TITLE
Drumkit Online Import Fail

### ISSUE THREAD

**Issue by NoAliby** [hydrogen-music/hydrogen-music#26]
The Drumkit Online Import Fails for a number of Sound Libraries.
It may be that the path to these are incorrect or the files do not exist in the repository.

**SYSTEM**
Hydrogen 1.1.1 win64
Windows 10 64bit

**EVENTS**
____________________________________
Online Import attempt
Repository as per install. I did not change this.
Repository set to http://www.hydrogen-music.org/feeds/drumkit_list.php
1. Open Hydrogen
2. Menu: Drumkit | Online Import
3. Select "YamahaVintageKit"
4. Click "Download and install"
5. A window opens and closes on the screen
6. No change, nothing installed
[hydrogen - YamahaVintageKit.log](https://github.com/hydrogen-music/hydrogen-music/files/7851416/hydrogen.-.YamahaVintageKit.log)

____________________________________
I can install from a local file downloaded from https://sourceforge.net/projects/hydrogen/files/Sound%20Libraries/Main%20sound%20libraries/
1. Open Hydrogen
2. Menu: Drumkit | Import
3. Select path to local file "YamahaVintageKit.h2drumkit"
4. Click "install"
5. A window opens "SoundLibrary imported in C:/User/Alistair/.hydrogen/data
6. Click OK, and you can see the "YamahaVintageKit" Sound Library appears in the Sound Library List 
7. Click Close
[hydrogen - YamahaVintageKit Local.log](https://github.com/hydrogen-music/hydrogen-music/files/7851446/hydrogen.-.YamahaVintageKit.Local.log)

____________________________________
Test Online Import on listed Kits

Sound Libary | Online Import
-- | --
Audiophob | Yes
belofilms | Yes
BJA_Pacific | Fail
JazzFunKit | Fail
Boss_DR-110 | Fail
Classic 3355606kit | Fail
Classic-626 | Fail
circAfrique v4 | Fail
ColomboAcousticDrumkit | Fail
YamahaVintageKit | Fail
DeathMetal | Fail
Denon CRB-90 | Yes
Drumkit exceptional | Yes
EasternHop | Fail
Electric EmpireKit | Fail
Ernys Percussion | Fail
Forzee Stereo | Fail
Gimme A Hand 1.0 | Fail
GSCW Kit 1 | Yes
GSCW Kit 2 | Yes
HardElectro1 | Fail
HipHop-1 | Fail
HipHop-2 | Fail
K-27_Trash_Kit | Fail
Lightning1024 | Fail
Millo-Drums 1 | Fail
Millo_MultiLayered2 | Fail
Millo_MultiLayered3 | Fail
Roland_MC_307_CR78&Cheaps | Yes
Roland_MC_307_TR-606 | Yes
Roland_MC_307_TR-808 | Yes
Roland_MC_307_TR-909 | Yes
Roland_MC_307_Techno1 | Yes
rumpf kit Z01 | Yes
SF3007-2011-Set-03 | Fail
Synthie-1 | Fail
TD-7kit | Fail
Techno-1 | Fail
The Black Pearl 1.0 | Fail
TR808909 | Fail
VariBreaks | Fail

[hydrogen - OI Test.log](https://github.com/hydrogen-music/hydrogen-music/files/7851541/hydrogen.-.OI.Test.log)
____________________________________

**Comment by theGreatWhiteShark** [comment]
Thanks for the thorough analysis! I'll have a look

**Comment by theGreatWhiteShark** [comment]
Seems this is a certificate error prohibiting a connection to https://nav.dl.sourceforge.net/project/hydrogen/Sound%20Libraries/Main%20sound%20libraries/YamahaVintageKit.h2drumkit . Also, it seems only Windows builds are affected as this works flawlessly under Linux.

It affects all kits stored on SourceForge. Those you were able to download are hosted at a different server http://hydro.smoors.de/ which does not required a working TLS connection.

**Comment by theGreatWhiteShark** [comment]
Hey @NoAliby ,

Could you test [Hydrogen-1.1.1-win64.exe](https://ci.appveyor.com/api/buildjobs/v7cfgvvygau8pcne/artifacts/Hydrogen-1.1.1-win64.exe) or [Hydrogen-1.1.1-win32.exe](https://ci.appveyor.com/api/buildjobs/eyk6bxbbqvj9rwwg/artifacts/Hydrogen-1.1.1-win32.exe) depending on your system and check whether you are now able to download the missing kits?

**Comment by NoAliby** [comment]
Yip, that works now.
(PS. the SVG interface makes SUCH a difference - looks great!)
