### ISSUE TITLE
Midi controlers

### ISSUE THREAD

**Issue by garciazavaleta** [hydrogen-music/hydrogen-music#4]
Hi, can I use my Yamaha DTX400 via Midi?

**Comment by trebmuh** [comment]
@garciazavaleta : this is not the right place for asking questions about Hydrogen, since this is the repository which hosts our website. Please see here: https://github.com/hydrogen-music/hydrogen for questions about using Hydrogen.

**Comment by mauser** [comment]
@garciazavaleta : In general you can use any midi-capable controller with Hydrogen. But since the Yamaha DTX 400 uses Midi via USB, things can be more complicated, but in the end it depends on your operating system's driver and not on Hydrogen.
