### ISSUE TITLE
Error opening file.

### ISSUE THREAD

**Issue by videosanonimos** [hydrogen-music/hydrogen-music#40]
When I try to open a project Hydrogen gives an error and no explanation.
If this is not quickly resolved I will look for another program.

Thanks!

Felipe

**Comment by trebmuh** [comment]
You're not on the right repo here. The one you are probably looking for is https://github.com/hydrogen-music/hydrogen .
Don't forget to pu more info to help helpers to help you (ie: operating system, hydrogen version,...).
