### ISSUE TITLE
Donate: "Buy us a beer" not available

### ISSUE THREAD

**Issue by ghost** [hydrogen-music/hydrogen-music#41]
Under your donation section on your webpage is described, there is a "By us a beer" Button to donate.

http://hydrogen-music.org/contribution/

But I didn't find it. Would it be possible to donate money?

Greetings Thomas

**Comment by ghost** [comment]
Okay, found it in the Application itself. But the contribute section should be updated anyway ;)

**Comment by theGreatWhiteShark** [comment]
> But the contribute section should be updated anyway

Yeah, I know. The whole web page needs some love. Well, maybe some day when most of Hydrogen's bugs are fixed :D
