### ISSUE TITLE
functionalities

### ISSUE THREAD

**Issue by tgtec** [hydrogen-music/hydrogen-music#5]
I'm new to Hydrogen (using the 1.0.0-beta1) and just finished my first song programming. With a bit of trial and error, the program is pretty easy to use - well done and thanks to you guys out there.
A few features I noticed missing:
- 'half-open hi-hat' as well as 'bell' without sound file
- changing drum sounds (attack, decay, pitch ...) doesn't work - coming later on?
It would be very cool to have a 'flam' function as well as a second crash cymbal to provide some variation in crash sounds.
Otherwise I'm pretty happy with the program,
cheers, Thomas

**Comment by trebmuh** [comment]
@tgtec  this is not the right place for this feature request report. Please, close this one and open another one on [the Hydrogen repository](https://github.com/hydrogen-music/hydrogen).

**Comment by theGreatWhiteShark** [comment]
That's mostly a feature request for a specific drumkit from a Github account only active once in 2019.

I'm closing this one due to age. Please feel free to reopen it.
