### ISSUE TITLE
C3 problem Not possible to reload imported drumkits

### ISSUE THREAD

**Issue by ChristianPB** [hydrogen-music/hydrogen-music#6]
When exporting to MIDI, all patterns play the same key (C3). A workaround was to reload the instrument. This works fine with the two default kits (System kits stored in the Applicationfolder during the installation) If i try to load an imported kit, all notes again are C3. I can not find where the imported kits are stored. Wanted to try to move them from the User drumkits to the System drumkits.

**Comment by trebmuh** [comment]
@ChristianPB this is not the right place for this bug report. Please, close this one and open another one on [the Hydrogen repository](https://github.com/hydrogen-music/hydrogen).

**Comment by trebmuh** [comment]
:+1:
