### ISSUE TITLE
Was working, saved a song in the works, crashed and won't restart.

### ISSUE THREAD

**Issue by NightfallFX** [hydrogen-music/hydrogen-music#7]
I was using the program for some months now. Had made several songs. While working on one, I tried to save my current work on it and the program crashed. Now it refuses to restart. I reinstalled the program. I renamed my song files to see if that was the issue. Yes and No, Yes the program starts, but now the frames of the program are all wonky. I tried to load the song I was working on(spent over a month working on), the program crashes again, refuses to start again. Using Win10.

**Comment by trebmuh** [comment]
@NightfallFX you're not on the right place to ask for hydrogen support. Please report [here](https://github.com/hydrogen-music/hydrogen).

**Comment by NightfallFX** [comment]
Ok thank you!

On July 31, 2019, at 8:11 PM, Olivier Humbert <notifications@github.com> wrote:

@NightfallFX you're not on the right place to ask for hydrogen support. Please report here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/hydrogen-music/hydrogen-music/issues/7?email_source=notifications">https://github.com/hydrogen-music/hydrogen-music/issues/7?email_source=notifications</a>\u0026email_token=AMYFTRHXJW3TPIZJQR3Z7VTQCISZVA5CNFSM4IIBVRUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3I5KEQ#issuecomment-517068050", "url": "<a href="https://github.com/hydrogen-music/hydrogen-music/issues/7?email_source=notifications">https://github.com/hydrogen-music/hydrogen-music/issues/7?email_source=notifications</a>\u0026email_token=AMYFTRHXJW3TPIZJQR3Z7VTQCISZVA5CNFSM4IIBVRUKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3I5KEQ#issuecomment-517068050", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by trebmuh** [comment]
@mauser I don't have specific rights here, hence I can't close this thread.

**Comment by NightfallFX** [comment]
Will do when I get to PC
